apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
  labels:
    app: moja-role-operator
    app.kubernetes.io/component: moja-role-operator
    app.kubernetes.io/instance: moja-role-operator
  name: moja-role-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: moja-role-operator
      app: moja-role-operator
  template:
    metadata:
      labels:
        deployment: moja-role-operator
        app: moja-role-operator
    spec:
      containers:
      - image: mojaloop/security-role-perm-operator-svc:local
        imagePullPolicy: Never
        name: moja-role-operator
        ports:
          - containerPort: 3001
            protocol: TCP
        env:
          - name: DEV_MODE
            value: 'false'
          - name: ROLE_PERM_OPERATOR_ORY_KETO_READ_SERVICE_URL
            value: 'http://moja-keto-service:4466'
          - name: ROLE_PERM_OPERATOR_ORY_KETO_WRITE_SERVICE_URL
            value: 'http://moja-keto-service:4467'
          - name: WATCH_RESOURCE_GROUP
            value: 'mojaloop.io'
          - name: WATCH_RESOURCE_VERSION
            value: 'v1'
          - name: WATCH_RESOURCE_PLURAL
            value: 'mojalooproles'
          - name: WATCH_NAMESPACE
            value: 'mojaloop'
      serviceAccount: moja-role-operator

---
apiVersion: v1
kind: Service
metadata:
  name: moja-role-operator
spec:
  selector:
    app: moja-role-operator
  type: NodePort
  ports:
    - name: api-port
      protocol: TCP
      port: 3001
      targetPort: 3001
