# permissions for end users to edit mojalooproles.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mojalooprole-editor-role
rules:
  - apiGroups:
      - mojaloop.io
    resources:
      - mojalooproles
      - mojaloop-permission-exclusions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mojaloop.io
    resources:
      - mojalooproles/status
      - mojaloop-permission-exclusions/status
    verbs:
      - get
      - list
      - watch
      - update
