apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mojalooprole-editor-role
subjects:
  - kind: ServiceAccount
    name: moja-role-operator
    namespace: mojaloop
